[package]
name = "Rust-Dropper"
version = "0.1.0"
authors = ["Erez Goldberg"]
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["memoryapi", "winnt"] }
reqwest = { version = "0.11", features = ["blocking"] }
