[package]
name = "shellcode_executor"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["memoryapi", "winnt"] }
reqwest = { version = "0.11", features = ["blocking"] }
